---

name: Snyk Security

on: push

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10'
      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Open Source
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          pip install -r requirements.txt
          snyk test
      - name: Snyk Code
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk code test
