---

name: Snyk Security

on: push

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for weaknesses and vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk SBOM
        run: snyk sbom
      - name: Snyk Open Source
        run: snyk test --all-projects --sarif > snyk-open-source.sarif
      - name: Snyk Code
        run: snyk code test --sarif > snyk-code.sarif
